version: '3'
services:
  redis:
    container_name: v-redis
    image: redis:5.0.3
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf:ro
      - ./data:/data
    command: redis-server /etc/redis/redis.conf