version: "3.4"
services:
  redis:
    image: redis:5.0.3
    restart: always
    container_name: redis5-master
    ports:
      - 6379:6379
      - 16379:16379
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./data:/data
      - ./conf/redis.conf:/etc/redis/redis.conf:ro