server:
  port: 8081
spring:
  redis:
    password: uHuQBSp6DSnD
    timeout: 1000
    database: 0  #默认有16个db(集群模式下无多db概念，取而代之是hash槽)，默认是第0个
    jedis:
      pool:
        max-active: 8 #最大连接数（使用负值表示没有限制） 默认 8
        max-wait: 1000 #最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8  #最大空闲连接 默认 8
        min-idle: 0
    cluster:
      nodes: 172.16.79.11:6368, 172.16.79.11:6378, 172.16.79.11:6388, 172.16.79.11:6369, 172.16.79.11:6379, 172.16.79.11:6389
      max-redirects: 5