version: "3.4"
services:
  redis1:
    image: redis:5.0.3
    restart: always
    container_name: redis5-m1
    ports:
    - 6368:6368
    - 16368:16368
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./6368/data:/data
      - ./6368/conf/redis.conf:/etc/redis/redis.conf:ro
    network_mode: host
  redis2:
    image: redis:5.0.3
    restart: always
    container_name: redis5-m2
    command: redis-server /etc/redis/redis.conf
    ports:
    - 6378:6378
    - 16378:16378
    volumes:
      - ./6378/data:/data
      - ./6378/conf/redis.conf:/etc/redis/redis.conf:ro
    network_mode: host
  redis3:
    image: redis:5.0.3
    restart: always
    container_name: redis5-m3
    command: redis-server /etc/redis/redis.conf
    ports:
    - 6388:6388
    - 16388:16388
    volumes:
      - ./6388/data:/data
      - ./6388/conf/redis.conf:/etc/redis/redis.conf:ro
    network_mode: host
  redis4:
    image: redis:5.0.3
    restart: always
    container_name: redis5-s1
    command: redis-server /etc/redis/redis.conf
    ports:
    - 6369:6369
    - 16369:16369
    volumes:
      - ./6369/data:/data
      - ./6369/conf/redis.conf:/etc/redis/redis.conf:ro
    network_mode: host
  redis5:
    image: redis:5.0.3
    restart: always
    container_name: redis5-s2
    command: redis-server /etc/redis/redis.conf
    ports:
    - 6379:6379
    - 16379:16379
    volumes:
      - ./6379/data:/data
      - ./6379/conf/redis.conf:/etc/redis/redis.conf:ro
    network_mode: host
  redis6:
    image: redis:5.0.3
    restart: always
    container_name: redis5-s3
    command: redis-server /etc/redis/redis.conf
    ports:
    - 6389:6389
    - 16389:16389
    volumes:
      - ./6389/data:/data
      - ./6389/conf/redis.conf:/etc/redis/redis.conf:ro
    network_mode: host
