server:
  port: 8888
spring:
  rabbitmq:
    host: 172.16.79.10
    #username: admin
    #password: Oqro55Mz
    username: guest
    password: guest
    port: 5673
user:
  rabbitmq:
    build:
      email:
        exchange: user
        queue: user.build.email
        route-key: user.build.email

